#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get install haproxy -y
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/haproxy/haproxy.cfg
sudo sed -i -e '$a\listen appname 0.0.0.0:80\n\tmode http\n\tstats enable' /etc/haproxy/haproxy.cfg
sudo sed -i -e '$a\\tbalance roundrobin\n\toption httpclose\n\toption forwardfor' /etc/haproxy/haproxy.cfg
sudo sed -i -e '$a\\tserver 1405-web-01 34.74.10.151:80\n\tserver 1405-web-02 35.237.23.115:80' /etc/haproxy/haproxy.cfg
sudo service haproxy start
