#!/usr/bin/env bash
#Process and PID file
while ((1))
do
    echo $$ > /var/run/holbertonscript.pid
    echo "To infinity and beyond"
    trap "echo I hate the kill command; sudo rm /var/run/holbertonscript.pid" SIGTERM
    trap "Y U no love me?!" SIGINT
    trap "sudo rm /var/run/holbertonscript.pid" SIGQUIT
    sleep 2
done
