#!/usr/bin/env bash
#Superstitious numbers
i=1
while (($i <= 20))
do
    if [ $i -eq 4 ]
    then
    echo -e $i "\nbad luck from China"
    elif [ $i -eq 9 ]
    then
    echo -e $i "\nbad luck from Japan"
    elif [ $i -eq 17 ]
    then
    echo -e $i "\nbad luck from Italy"
    else
    echo $i
    fi
    i=$((i+1))
done
